print('Welcome to the Band Name Generator')
print('What is the name of the city you grew in ?')
city = input()
print("What is your Pets name?")
pet =input()
print("Your band name could be {} {}".format(city,pet))
